/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Directorio.vistas;

import Directorio.Directorio;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {
private Directorio agenda = new Directorio();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmSalir = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmAgregarC = new javax.swing.JMenuItem();
        jmBuscarC = new javax.swing.JMenuItem();
        jmBorrarC = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        jMenu2.setText("Directorio");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jmAgregarC.setText("Agregar Cliente");
        jmAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarCActionPerformed(evt);
            }
        });
        jMenu2.add(jmAgregarC);

        jmBuscarC.setText("Buscar Cliente");
        jmBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarCActionPerformed(evt);
            }
        });
        jMenu2.add(jmBuscarC);

        jmBorrarC.setText("Borrar Cliente");
        jmBorrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBorrarCActionPerformed(evt);
            }
        });
        jMenu2.add(jmBorrarC);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarCActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        AgregarClienteView acv=new AgregarClienteView(agenda);
        acv.setVisible(true);
        escritorio.add(acv);
        escritorio.moveToFront(acv);
        escritorio.repaint();
        
    }//GEN-LAST:event_jmAgregarCActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
	escritorio.removeAll();
        BuscarClienteView bcv=new BuscarClienteView(agenda);
        bcv.setVisible(true);
        escritorio.add(bcv);
        escritorio.moveToFront(bcv);
        escritorio.repaint();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jmBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarCActionPerformed
        // TODO add your handling code here:
	escritorio.removeAll();
        BuscarClienteView bcv=new BuscarClienteView(agenda);
        bcv.setVisible(true);
        escritorio.add(bcv);
        escritorio.moveToFront(bcv);
        escritorio.repaint();
    }//GEN-LAST:event_jmBuscarCActionPerformed

    private void jmBorrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBorrarCActionPerformed
        // TODO add your handling code here:
	escritorio.removeAll();
	BorrarCliente brc = new BorrarCliente(agenda);
	brc.setVisible(true);
	escritorio.add(brc);
        escritorio.moveToFront(brc);
        escritorio.repaint();
	
    }//GEN-LAST:event_jmBorrarCActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
	setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmAgregarC;
    private javax.swing.JMenuItem jmBorrarC;
    private javax.swing.JMenuItem jmBuscarC;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
